#!/usr/bin/env python3
# /// script
# requires-python = ">=3.11"
# dependencies = ["pillow>=11.0"]
# ///
"""Publish the illustrations into the site: webp files plus the CSS that binds them to cards.

The PNGs are two megabytes apiece and must not go into the repository. This writes a webp per post
per scheme into `docs/assets/blog/`, and generates the stylesheet block that attaches them to the
card visuals.

No markup changes: a card is `<a class="bdr-card" href=".../<slug>/">`, so an attribute selector on
the href reaches every listing at once -- the blog index, the home page and any category page that
grows cards later -- without touching a single one of them.
"""

from __future__ import annotations

import argparse
from pathlib import Path

from PIL import Image

HERE = Path(__file__).resolve().parent
SITE = HERE.parent

BANNER = """
/* -------- 15. Per-post card illustrations --------
   Generated by articles-images-prompts/publish_images.py -- do not hand-edit.
   One rule per post, matched on the slug in the card's href, so no listing markup
   carries an image reference. The slate block swaps in the dark-scheme render,
   derived from the same drawing by dark_variant.py. */

.bdr-card__visual,
.bdr-featured__visual,
.bdr-post__hero {
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
}

/* The article hero. Lines up with the prose column rather than the full grid:
   the body text is capped at 42rem, and an image wider than the paragraphs it
   introduces reads as a banner instead of as part of the article. */
.bdr-post__hero {
  max-width: 42rem;
  margin: 0 auto 2.25rem;
  aspect-ratio: 16 / 10;
  border-radius: 12px;
  border: 1px solid var(--bdr-border);
  background-color: var(--bdr-surface-2);
}
"""


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    p.add_argument("--light", type=Path, default=HERE / "images/v2/normalized")
    p.add_argument("--dark", type=Path, default=HERE / "images/v2/dark")
    p.add_argument("--assets", type=Path, default=SITE / "docs/assets/blog")
    p.add_argument("--css", type=Path, default=SITE / "docs/stylesheets/bedrock.css")
    p.add_argument("--width", type=int, default=1200)
    p.add_argument("--quality", type=int, default=80)
    args = p.parse_args()

    args.assets.mkdir(parents=True, exist_ok=True)
    rules_light, rules_dark, total = [], [], 0

    for light in sorted(args.light.glob("*.png")):
        slug = light.stem
        dark = args.dark / light.name
        if not dark.exists():
            raise SystemExit(f"no dark variant for {slug}")
        for src, name in ((light, f"{slug}.webp"), (dark, f"{slug}-dark.webp")):
            with Image.open(src) as im:
                im = im.convert("RGB")
                h = round(im.height * args.width / im.width)
                im = im.resize((args.width, h), Image.LANCZOS)
                out = args.assets / name
                im.save(out, format="WEBP", quality=args.quality, method=6)
                total += out.stat().st_size
        rules_light.append(
            f'.bdr-card[href*="{slug}"] .bdr-card__visual,\n'
            f'.bdr-post__hero[data-bdr-post="{slug}"] {{\n'
            f'  background-image: url("../assets/blog/{slug}.webp");\n}}'
        )
        rules_dark.append(
            f'[data-md-color-scheme="slate"] .bdr-card[href*="{slug}"] .bdr-card__visual,\n'
            f'[data-md-color-scheme="slate"] .bdr-post__hero[data-bdr-post="{slug}"] {{\n'
            f'  background-image: url("../assets/blog/{slug}-dark.webp");\n}}'
        )

    css = args.css.read_text(encoding="utf-8")
    marker = "/* -------- 15. Per-post card illustrations"
    if marker in css:
        css = css[: css.index(marker)].rstrip() + "\n"
    block = BANNER + "\n" + "\n".join(rules_light) + "\n\n" + "\n".join(rules_dark) + "\n"
    args.css.write_text(css.rstrip() + "\n" + block, encoding="utf-8")

    print(f"{len(rules_light)} posts, {2 * len(rules_light)} webp files, "
          f"{total / 1024 / 1024:.1f} MB total")
    print(f"assets: {args.assets}")
    print(f"css:    {args.css}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
